apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ift5
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: ift5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ift5
    spec:
      containers:
        - image: ilyakuz26/ift2:v2
          name: ift2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "1000Mi"
            limits:
              cpu: "50m"
              memory: "1000Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 1
            periodSeconds: 5
            timeoutSeconds: 1
            initialDelaySeconds: 5
